server:
  port: 8081
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  config:
    import: application-dal.yml


database:
  name: personnel

jwt:
  key: sys-key

security:
  salt: sys-salt
  salt-index: 2

msg:
  welcome: "Welcome！"